### ISSUE TITLE
Reads name  invalid error

### ISSUE THREAD

**Issue by shangshanzhizhe** [mkirsche/RefineInsertions#2]
Hi,
Amazing CELL article and this software! I'm trying to add the sequence information of insertions to the vcf file. my samples were sequenced using ONT and aligned using NGLMR. when I run the Iris, it told me that my reads' name was invalid.  Below is my .bam file looks like:
![image](https://user-images.githubusercontent.com/29882626/92691857-dba57b80-f375-11ea-9923-a77908eccd32.png)

What should I do to fix this problem? Thanks for your help!

**Comment by mkirsche** [comment]
Hi,

Thanks for your interest in the software! Those alignment entries look fine, so an invalid read names error is likely referring to the VCF file.  What did you use to generate your SV calls?  Iris requires an RNAMES INFO field which indicates a list of supporting reads for each variant (I just updated the README file to indicate this).  If you are using Sniffles for variant calling, this field is enabled with the parameter "-n -1".  If you already have this field present in all of your variants and this is not the issue, could you please provide an example of the error message, and if you are able to share it, an example of an insertion-type variant call which you are passing to Iris?

Thanks!
Melanie

**Comment by shangshanzhizhe** [comment]
Hi, 

Glad to tell you that adding flag '-n -1' of Sniffles worked for me. Thanks a lot!

Shangzhe

**Comment by mkirsche** [comment]
Hi Shangzhe,

I'm glad to hear that!  I'll go ahead and close this Github issue, but please don't hesitate to reach out if you have other problems!

Best,
Melanie
