### ISSUE TITLE
Skipped Insertions because there is no sequence ?

### ISSUE THREAD

**Issue by Adifo** [mkirsche/RefineInsertions#3]
Hello Melanie,

I am trying to use Iris to retrieve structural variant sequence in a VCF for merging purpose (instead of a N \<INS\>). My VCF was obtained from sniffles and I've retrieved the RNAMES fields but Iris still fail to fix insertion type variants.

Here one example

`1       20836   0_0     N       <INS>   .       PASS    IMPRECISE;SVMETHOD=Snifflesv1.0.10;CHR2=1;END=20928;STD_quant_start=44;STD_quant_stop=50;Kurtosis_quant_start=-1;Kurtosis_quant_stop=0;SVTYPE=INS;RNAMES=4154b2d3-1c38-41b5-8a7f-26c4672fb4e1,5a5c65a1-643b-4cda-99c3-0b9efc34857f,b7da30cd-5039-44d4-bbdb-21ac84f05638,fa1edabb-3267-4979-8dcf-8a4750d8acbc;SUPTYPE=AL;SVLEN=46;STRANDS=+-;STRANDS2=4,0,4,0;RE=4;REF_strand=3,0;AF=0.571429    GT:DR:DV
        0/1:3:4`

and it gives the following message

`Skipping 1:20836:INS:0_0 because there is no sequence (time = 00:00:00:04.754)`

I have checked my vcf files and no insertion has been fixed (>20000, deletion were ok). I have also looked at my bam file for the reads reported in the RNAMES fields and I had no issue to found them.

So, in the end, I do not get why variants are skipped. I would like to know if I have an issue or if it actually fails at the reads assembly but it seems weird that it affects all my variants.

I am using the conda version of Iris (irissv) avaible with Jasmine.

Thank you for your help !

**Comment by mkirsche** [comment]
Hi,

In trying to refine insertion sequences, Iris assumes that you already have some insertion sequence to start with.  This can be either encoded as a SEQ INFO field, or as the ALT allele (with the REF allele being the reference base being right before the insertion, and the ALT being that base plus the insertion sequence).  In my experience running Sniffles, it typically includes this sequence for most or all insertions.  What version and parameters are you using for Sniffles variant calling?

Thanks,
Melanie

**Comment by Adifo** [comment]
I am using sniffles 1.0.10. Here is my command \:

> sniffles -t 10 -s 3 --genotype --cluster --report_read_strands -n -1 -m \<BAM\> -v \<VCF\>

I guess I am missing the `--report_seq` arguments ? I did not set it as it was beta

Could I ask why you need an initial sequence ? I thought producing a local assembly with the retrieved reads would give a sequence template as good as what sniffles could output. Are you using the SEQ/ALT field as a template for reads mapping ?

Thank you for your quick answer.

**Comment by mkirsche** [comment]
Yes I think that adding the report_seq argument should fix it based on the Sniffles docs - sorry for the confusion there!

And that's exactly right - we're using the initial sequence as a starting point, mapping the reads to that, and then using those alignments along with the program racon to polish the sequence.  If you are unable to get the sequences, you could try using FalconSense (a local assembly module from an older version of the Canu assembler) by installing Iris from source and passing Iris the --falconsense flag.  However, we have found much better runtime and sequence accuracy can be obtained from more of a polishing approach based on the initial variant call, and it is likely that we will be removing FalconSense support in the future. 

Best,
Melanie
