### ISSUE TITLE
no error in absence of bam index

### ISSUE THREAD

**Issue by wdecoster** [mkirsche/RefineInsertions#4]
Hi,

Although it's obviously my fault for forgetting to index the bam, I think the messaging about this could be clearer. Iris does not report something is wrong, but rather returns that there are 0 relevant reads for each variant. It took me a while to figure out what was wrong, and I think this should be an error.

Wouter

**Comment by mkirsche** [comment]
Hi Wouter,

Thanks a lot for the suggestion, and sorry about any extra frustration with debugging it! I'll add a check for that sometime in the next few days and will let you know when it's been updated.

Thank you,
Melanie

**Comment by mkirsche** [comment]
Hi Wouter,

I resolved this issue by having Iris automatically check for the presence of a BAM index and use samtools to create it if it is missing, and this will be added as part of the next conda release.  Please let me know if you continue to have this problem!

Best,
Melanie

**Comment by wdecoster** [comment]
Thanks!
