### ISSUE TITLE
The max out lengths for deletion?

### ISSUE THREAD

**Issue by JYLeeBioinfo** [mkirsche/RefineInsertions#7]
Hello,

I have a question regarding the deletion refinement option.

When the option  --also_deletions is set,
are the deletions that have lengths > max_out_length also removed?
Or are those deletions retained in the final call?

Jin-Young

**Comment by mkirsche** [comment]
Hi Jin-Young,

Yes, all variants that have the absolute value of their length greater than that threshold regardless of whether or not they were refined.  --also_deletions just refers to allowing their breakpoints to be refined in a manner similar to how insertions are refined.  If you want to keep them around though, you can use the --keep_long_variants parameter.

Best,
Melanie

**Comment by JYLeeBioinfo** [comment]
Thank you for your prompt reply!
